// Code generated by "stringer -type=Code -linecomment"; DO NOT EDIT.

package anytool

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CodeFeatureNotSupport-1000]
	_ = x[CodeOperationFailed-1001]
	_ = x[CodeInvalidArguments-1002]
	_ = x[CodeExistYet-1003]
}

const _Code_name = "feature Not supportoperate failedInvalid argumentsexist yet"

var _Code_index = [...]uint8{0, 19, 33, 50, 59}

func (i Code) String() string {
	i -= 1000
	if i < 0 || i >= Code(len(_Code_index)-1) {
		return "Code(" + strconv.FormatInt(int64(i+1000), 10) + ")"
	}
	return _Code_name[_Code_index[i]:_Code_index[i+1]]
}
